name: Update README Last Updated Badge

on:
  push:
    branches:
      - main  # Adjust this to the branch where changes are made

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit date
        id: get-date
        run: echo "LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%B %d, %Y')" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i "s/\[Last Updated\](.*)/\[Last Updated\](https:\/\/img.shields.io\/badge\/last%20updated-${{ env.LAST_COMMIT_DATE// /%20}}-brightgreen)/" README.md

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README.md with last updated date"
          git push
